### health
GET http://localhost:8080/actuator/health

### shutdown
POST http://localhost:8080/actuator/shutdown

###
POST http://localhost:8080/api/translate/v1/translation
Content-Type: application/json

{
  "from": "eng",
  "to": "rus",
  "text": "able"
}