spring:
  application:
    name: rest_api_interface

  config:
    import: optional:file:.env[.properties]

  lifecycle:
    timeout-per-shutdown-phase: 1m

server:
  shutdown: graceful

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,shutdown

logging:
  level:
    com.malex.rest_api_interface.controller.RestApiController: DEBUG
